#  run me with: docker-compose -f docker-compose.dev.yml up --build

version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: TicTacToe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./BE
      dockerfile: CloudTicTacToeBackend/CloudTicTacToe.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_URLS: http://+;https://+
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: Host=postgres;Port=5432;Username=postgres;Password=Password1;Database=TicTacToe;
      AllowedOrigins: http://localhost:4200,http://192.168.0.136:4200
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - postgres

  web:
    build: 
      context: ./Fe/CloudTicTacToe
    environment:
      API_BASE_URL: https://localhost:8082
    ports:
      - 4200:4200
