#  run me with: docker-compose -f docker-compose.in-memory.yml up 

version: '3.8'

services:
  api:
    image: macioszczykmikolaj/tictactoe-api:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: Server=postgres;Port=5432;Database=TicTacToe;User Id=postgres;Password=Pa55w0rd;
      AllowedOrigins: http://publicUrl:4200
      UseInMemoryDb: true
    ports:
      - "8080:80"
      - "8082:443"

  web:
    image: macioszczykmikolaj/tictactoe-web:latest
    environment:
      API_BASE_URL: http://publicUrl:8080
    ports:
      - 4200:4200
