#  run me with: docker-compose -f docker-compose.dev.yml up --build

version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: TicTacToe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55w0rd
    ports:
      - "5432:5432"

  api:
    build: 
      context: ./BE
      dockerfile: CloudTicTacToeBackend/CloudTicTacToe.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: Server=postgres;Port=5432;Database=TicTacToe;User Id=postgres;Password=Pa55w0rd;
      AllowedOrigins: http://localhost:4200,http://192.168.0.136:4200
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - postgres

  web:
    build: 
      context: ./Fe/CloudTicTacToe
    environment:
      API_BASE_URL: http://192.168.0.136:8080
    ports:
      - 4200:4200
