#  run me with: docker-compose up

version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: TicTacToe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pa55w0rd
    ports:
      - "5432:5432"

  api:
    image: macioszczykmikolaj/tictactoe-api:latest
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: Host=postgres;Port=5432;Database=TicTacToe;User Id=postgres;Password=Pa55w0rd;
      AllowedOrigins: http://publicUrl:4200
    ports:
      - "8080:80"
      - "8082:443"
    depends_on:
      - postgres

  web:
    image: macioszczykmikolaj/tictactoe-web:latest
    environment:
      API_BASE_URL: http://publicUrl:8080
    ports:
      - 4200:4200
