#  run me with: docker-compose -f docker-compose.dev-in-memory.yml up

version: '3.8'

services:
  api:
    build: 
      context: ./BE
      dockerfile: CloudTicTacToeBackend/CloudTicTacToe.API/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__PostgreSQLConnection: Server=postgres;Port=5432;Database=TicTacToe;User Id=postgres;Password=Pa55w0rd;
      AllowedOrigins: http://localhost:4200,http://192.168.0.136:4200
      UseInMemoryDb: true
    ports:
      - "8080:80"
      - "8082:443"

  web:
    build: 
      context: ./Fe/CloudTicTacToe
    environment:
      API_BASE_URL: http://192.168.0.136:8080
    ports:
      - 4200:4200
